### ISSUE TITLE
Requesting to add 'Carbon Wallet' to the 'Wallets' category

### ISSUE THREAD

**Issue by Flaez** [Flaez/acceptbitcoincash-staging#14]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. A

---------------
Requesting to add 'Carbon Wallet' to the 'Wallets' category. Details follow:

```yml

- name: Carbon Wallet 
      url: http://google.com
      img: 
      twitter: Carbon_wallet
      email_address: john@carbonwallet.com
      btc: Yes
      bch: Yes
      othercrypto: Yes
      doc: https://www.reddit.com/r/Bitcoincash/comments/7vg4is/carbon_wallet_now_live_with_support_for_bch/
```
