### ISSUE TITLE
Add 'pyxpub.io' to the 'Payments' category

### ISSUE THREAD

**Issue by Flaez** [Flaez/acceptbitcoincash-staging#16]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Add 'pyxpub.io' to the 'Payments' category. Details follow:

```yml

- name: pyxpub.io
      url: https://pyxpub.io/
      img: 
      twitter: pyxpub
      email_address: info@pyxpub.io
      bch: Yes
      btc: Yes
      othercrypto: Yes
```
