### ISSUE TITLE
Add 'Takeaway' to the 'Food' category

### ISSUE THREAD

**Issue by Flaez** [Flaez/acceptbitcoincash-staging#18]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Add 'Takeaway' to the 'Food' category. Details follow:

```yml

- name: Takeaway
      url: https://www.takeaway.com/
      img: 
      twitter: takeaway
      region: eu
      bch: Yes
      btc: Yes
      othercrypto: No
```
