### ISSUE TITLE
Add 'Mobile Vikings' to the 'Utilities' category

### ISSUE THREAD

**Issue by Flaez** [Flaez/acceptbitcoincash-staging#20]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Add 'Mobile Vikings' to the 'Utilities' category. Details follow:

```yml
- name: Mobile Vikings
      url: https://mobilevikings.be/en/v2/
      img: 
      twitter: mobilevikingsBE
      facebook: mobilevikings
      email_address: info@mobilevikings.be
      region: eu
      country: BE
      bch: Yes
      btc: Yes
      othercrypto: No
```
