### ISSUE TITLE
Add 'CJS CD Keys' to the 'Gaming' category

### ISSUE THREAD

**Issue by Flaez** [Flaez/acceptbitcoincash-staging#23]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Add 'CJS CD Keys' to the 'Gaming' category. Details follow:

```yml
- name: CJS CD Keys
      url: https://www.cjs-cdkeys.com
      img: 
      twitter: @CJS_CD_Keys
      facebook: https://www.facebook.com/CJSCDKEYS
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: No
```
