### ISSUE TITLE
Add 'Digital Keys' to the 'Crypto-service' category

### ISSUE THREAD

**Issue by Flaez** [Flaez/acceptbitcoincash-staging#25]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Add 'Digital Keys' to the 'Crypto-service' category. Details follow:

```yml
- name: Digital Keys
      url: http://digitalkeys.biz/
      img: 
      email_address: digitalkeysshop@gmail.com
      btc: Yes
      othercrypto: Yes
```
