### ISSUE TITLE
Add 'Takeaway' to the 'Food' category

### ISSUE THREAD

**Issue by Flaez** [Flaez/acceptbitcoincash-staging#28]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Add 'Takeaway' to the 'Food' category. Details follow:

```yml
- name: Takeaway
      url: https://www.takeaway.com/
      img: https://pbs.twimg.com/profile_images/657109081652498432/NzSxDEOq_400x400.png
      twitter: takeaway
      bch: Yes
```

Add more information here if necessary.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
