### ISSUE TITLE
Add 'Mobile Vikings' to the 'Utilities' category

### ISSUE THREAD

**Issue by Flaez** [Flaez/acceptbitcoincash-staging#30]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Add 'Mobile Vikings' to the 'Utilities' category. Details follow:

```yml
- name: Mobile Vikings
      url: https://mobilevikings.be/en/v2/
      img: 
      twitter: mobilevikingsBE
      facebook: mobilevikings
      email_address: info@mobilevikings.be
      region: eu
      country: BE
      bch: Yes
      btc: Yes
      othercrypto: No
```

Add more information here if necessary.

For 2-letter _region_ codes, use:

Code | Name
-- | --
af | Africa
na | North America
oc | Oceania
an | Antarctica
as | Asia
eu | Europe
sa | South America

For 2-letter _country_ codes, use [ISO_3166-1_alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2#Officially_assigned_code_elements) codes.
