### ISSUE TITLE
Add 'Usenet Bucket' to the 'Hosting' category

### ISSUE THREAD

**Issue by Flaez** [Flaez/acceptbitcoincash-staging#32]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Add 'Usenet Bucket' to the 'Hosting' category. Details follow:

```yml
- name: Usenet Bucket
      url: http://t.co/zF9unElAWM
      img: 
      twitter: UsenetBucket
      region: eu
      bch: Yes
      btc: Yes
      othercrypto: No
```
