### ISSUE TITLE
Greenpack.ch

### ISSUE THREAD

**Issue by alt-win** [Flaez/acceptbitcoincash-staging#43]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add {{**greenpack.ch**}} to the {{**other**}} category. Details follow:

```yml

- name: Green_Pack_Shop
  url: http://greenpack.ch
  img: https://i.ibb.co/vk47Fd7/twitter-logo-400x400.jpg
  twitter: greenpackshop
  facebook: 
  region: eu
  country: CH
  city: Wuppenau
  bch: yes
  btc: no
  othercrypto: no
  doc: Monica_BCA_Discord
```

Add more information here if necessary.

Image is 32x32 despite image name.  Company website is currently offline.  This should be resolved by Jan 28th 2019.  They might accept other cryptos.  I don't know yet, so I just put no for now.
