### ISSUE TITLE
Requesting to add 'Carbon Wallet' to the 'Wallets' category.

### ISSUE THREAD

**Issue by Flaez** [Flaez/acceptbitcoincash-staging#5]
**Submission Notes:** Please fill in the template below, and don't worry about exact formatting, just do your best! Use the _**Preview**_ tab to check your submission before sending it. Help for **region/country 2-letter codes** are below.

---------------
Requesting to add 'Carbon Wallet' to the 'Wallets' category. Details follow:

```yml
- name: Carbon Wallet 
      img: 
      twitter: Carbon_wallet
      email_address: john@carbonwallet.com
      bch: Yes
      btc: Yes
      othercrypto: Yes
      doc: https://www.reddit.com/r/Bitcoincash/comments/7vg4is/carbon_wallet_now_live_with_support_for_bch/
```
I forgot to include the url above!
